### ISSUE TITLE
番剧列表篇

### ISSUE THREAD

**Issue by MaQiansen** [WowYiJiu/WowYiJiu.github.io#1]
佬，请问番剧页面是自己写的html还是通过主题框架生成的
![NXZ7@O2I``N _N0 TXZ80J3](https://user-images.githubusercontent.com/102568805/205297607-bf53f4f5-63ee-40f3-8f14-aea92ed6ed4d.png)

**Comment by WowYiJiu** [comment]
> 佬，请问番剧页面是自己写的html还是通过主题框架生成的 ![NXZ7@O2I``N _N0 TXZ80J3](https://user-images.githubusercontent.com/102568805/205297607-bf53f4f5-63ee-40f3-8f14-aea92ed6ed4d.png)
https://github.com/HCLonely/hexo-bilibili-bangumi
我用的这个插件

**Comment by WowYiJiu** [comment]
> 佬，请问番剧页面是自己写的html还是通过主题框架生成的 ![NXZ7@O2I``N _N0 TXZ80J3](https://user-images.githubusercontent.com/102568805/205297607-bf53f4f5-63ee-40f3-8f14-aea92ed6ed4d.png)
https://github.com/HCLonely/hexo-bilibili-bangumi
我用的这个插件

**Comment by WowYiJiu** [comment]
@YaYiJiang https://github.com/HCLonely/hexo-bilibili-bangumi
我用的这个插件

**Comment by YaYiJiang** [comment]
感谢大佬！
